### ISSUE TITLE
Support automatic installation of `norouter binary` to remote hosts

### ISSUE THREAD

**Issue by AkihiroSuda** [norouter/norouter#9]
Currently, user needs to install `norouter` binary to all the remote hosts manually.

This could be automatically installed using a new YAML field `.install.shCmd` like this:

```yaml
hosts:
# uses norouter binary that is already installed (as in the current version)
  host1:
    cmd: ["docker", "exec", "-i", "host1", "norouter"]
# NEW: install norouter binary automatically using `norouter show-installer`
  host2:
    install:
      shCmd: ["docker", "exec", "-i", "hostw", "sh"]
```
